sudo: required

language: python

python:
- '3.6'

install:
- pip install poetry
- poetry install

script:
- poetry run pytest

after_success:
- codecov

notifications:
  email:
    on_success: never # default: change
    on_failure: never # default: always
